/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BestSellingSearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BestSellingSearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.BestSellingSearchResponse = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.BestSellingSearchItem);
  }
}(this, function(ApiClient, BestSellingSearchItem) {
  'use strict';



  /**
   * The BestSellingSearchResponse model module.
   * @module model/BestSellingSearchResponse
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>BestSellingSearchResponse</code>.
   * Response body of a best selling search 
   * @alias module:model/BestSellingSearchResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>BestSellingSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BestSellingSearchResponse} obj Optional instance to populate.
   * @return {module:model/BestSellingSearchResponse} The populated <code>BestSellingSearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [BestSellingSearchItem]);
      }
    }
    return obj;
  }

  /**
   * List of best selling products 
   * @member {Array.<module:model/BestSellingSearchItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


