/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageSearchCategory', 'model/ImageSearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageSearchCategory'), require('./ImageSearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ImageSearchResponse = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.ImageSearchCategory, root.AliseeksApi.ImageSearchItem);
  }
}(this, function(ApiClient, ImageSearchCategory, ImageSearchItem) {
  'use strict';



  /**
   * The ImageSearchResponse model module.
   * @module model/ImageSearchResponse
   * @version 1.0.0-rc.1
   */

  /**
   * Constructs a new <code>ImageSearchResponse</code>.
   * Response from realtime image search 
   * @alias module:model/ImageSearchResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ImageSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageSearchResponse} obj Optional instance to populate.
   * @return {module:model/ImageSearchResponse} The populated <code>ImageSearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], [ImageSearchCategory]);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [ImageSearchItem]);
      }
      if (data.hasOwnProperty('selectedCategoryId')) {
        obj['selectedCategoryId'] = ApiClient.convertToType(data['selectedCategoryId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The eligible categories that apply to this image search response 
   * @member {Array.<module:model/ImageSearchCategory>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * The items that match the image 
   * @member {Array.<module:model/ImageSearchItem>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * The category ID which is selected 
   * @member {Number} selectedCategoryId
   */
  exports.prototype['selectedCategoryId'] = undefined;



  return exports;
}));


