/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PriceRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PriceRange'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.PriceSummary = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.PriceRange);
  }
}(this, function(ApiClient, PriceRange) {
  'use strict';



  /**
   * The PriceSummary model module.
   * @module model/PriceSummary
   * @version 1.0.2-rc.1
   */

  /**
   * Constructs a new <code>PriceSummary</code>.
   * A summary of prices for a product 
   * @alias module:model/PriceSummary
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>PriceSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceSummary} obj Optional instance to populate.
   * @return {module:model/PriceSummary} The populated <code>PriceSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('originalAmount')) {
        obj['originalAmount'] = PriceRange.constructFromObject(data['originalAmount']);
      }
      if (data.hasOwnProperty('unitOriginalAmount')) {
        obj['unitOriginalAmount'] = PriceRange.constructFromObject(data['unitOriginalAmount']);
      }
      if (data.hasOwnProperty('discountedAmount')) {
        obj['discountedAmount'] = PriceRange.constructFromObject(data['discountedAmount']);
      }
      if (data.hasOwnProperty('unitDiscountedAmount')) {
        obj['unitDiscountedAmount'] = PriceRange.constructFromObject(data['unitDiscountedAmount']);
      }
      if (data.hasOwnProperty('bulkAmount')) {
        obj['bulkAmount'] = PriceRange.constructFromObject(data['bulkAmount']);
      }
      if (data.hasOwnProperty('unitBulkAmount')) {
        obj['unitBulkAmount'] = PriceRange.constructFromObject(data['unitBulkAmount']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PriceRange} originalAmount
   */
  exports.prototype['originalAmount'] = undefined;
  /**
   * @member {module:model/PriceRange} unitOriginalAmount
   */
  exports.prototype['unitOriginalAmount'] = undefined;
  /**
   * @member {module:model/PriceRange} discountedAmount
   */
  exports.prototype['discountedAmount'] = undefined;
  /**
   * @member {module:model/PriceRange} unitDiscountedAmount
   */
  exports.prototype['unitDiscountedAmount'] = undefined;
  /**
   * @member {module:model/PriceRange} bulkAmount
   */
  exports.prototype['bulkAmount'] = undefined;
  /**
   * @member {module:model/PriceRange} unitBulkAmount
   */
  exports.prototype['unitBulkAmount'] = undefined;



  return exports;
}));


