/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ProductTransaction = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ProductTransaction model module.
   * @module model/ProductTransaction
   * @version 1.0.4
   */

  /**
   * Constructs a new <code>ProductTransaction</code>.
   * A transaction (order) of a product 
   * @alias module:model/ProductTransaction
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ProductTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductTransaction} obj Optional instance to populate.
   * @return {module:model/ProductTransaction} The populated <code>ProductTransaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('countryCode')) {
        obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
      }
      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('unit')) {
        obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
      }
    }
    return obj;
  }

  /**
   * The total number of transactions 
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Username who ordered the product 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Country code where the product was ordered 
   * @member {String} countryCode
   */
  exports.prototype['countryCode'] = undefined;
  /**
   * Country code where the product was ordered 
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * Date the product was ordered 
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * The unit string for describing the quantity 
   * @member {String} unit
   */
  exports.prototype['unit'] = undefined;



  return exports;
}));


