/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ProductRequestComponent = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ProductRequestComponent.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "shipping"
     * @const
     */
    "shipping": "shipping",
    /**
     * value: "html_description"
     * @const
     */
    "html_description": "html_description",
    /**
     * value: "variations"
     * @const
     */
    "variations": "variations"  };

  /**
   * Returns a <code>ProductRequestComponent</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ProductRequestComponent} The enum <code>ProductRequestComponent</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


