/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/IntegerRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./IntegerRange'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ProductShippingOptions = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.Amount, root.AliseeksApi.IntegerRange);
  }
}(this, function(ApiClient, Amount, IntegerRange) {
  'use strict';



  /**
   * The ProductShippingOptions model module.
   * @module model/ProductShippingOptions
   * @version 1.0.0-rc.1
   */

  /**
   * Constructs a new <code>ProductShippingOptions</code>.
   * Product shipping option 
   * @alias module:model/ProductShippingOptions
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ProductShippingOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductShippingOptions} obj Optional instance to populate.
   * @return {module:model/ProductShippingOptions} The populated <code>ProductShippingOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
      if (data.hasOwnProperty('tracking')) {
        obj['tracking'] = ApiClient.convertToType(data['tracking'], 'Boolean');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = Amount.constructFromObject(data['amount']);
      }
      if (data.hasOwnProperty('discount')) {
        obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
      }
      if (data.hasOwnProperty('commitDays')) {
        obj['commitDays'] = ApiClient.convertToType(data['commitDays'], 'Number');
      }
      if (data.hasOwnProperty('shipFrom')) {
        obj['shipFrom'] = ApiClient.convertToType(data['shipFrom'], 'String');
      }
      if (data.hasOwnProperty('deliveryTime')) {
        obj['deliveryTime'] = IntegerRange.constructFromObject(data['deliveryTime']);
      }
    }
    return obj;
  }

  /**
   * The shipping company 
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * The name of the shipping service 
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;
  /**
   * Whether or no the shipping option has tracking 
   * @member {Boolean} tracking
   */
  exports.prototype['tracking'] = undefined;
  /**
   * @member {module:model/Amount} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * The discount currently on this shipping option 
   * @member {Number} discount
   */
  exports.prototype['discount'] = undefined;
  /**
   * The number of days that are commited for this shipping option 
   * @member {Number} commitDays
   */
  exports.prototype['commitDays'] = undefined;
  /**
   * The place where the shipping comes from 
   * @member {String} shipFrom
   */
  exports.prototype['shipFrom'] = undefined;
  /**
   * @member {module:model/IntegerRange} deliveryTime
   */
  exports.prototype['deliveryTime'] = undefined;



  return exports;
}));


