/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ProductReview = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ProductReview model module.
   * @module model/ProductReview
   * @version 1.0.4
   */

  /**
   * Constructs a new <code>ProductReview</code>.
   * The product review 
   * @alias module:model/ProductReview
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ProductReview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductReview} obj Optional instance to populate.
   * @return {module:model/ProductReview} The populated <code>ProductReview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('buyerName')) {
        obj['buyerName'] = ApiClient.convertToType(data['buyerName'], 'String');
      }
      if (data.hasOwnProperty('buyerCountry')) {
        obj['buyerCountry'] = ApiClient.convertToType(data['buyerCountry'], 'String');
      }
      if (data.hasOwnProperty('buyerRating')) {
        obj['buyerRating'] = ApiClient.convertToType(data['buyerRating'], 'Number');
      }
      if (data.hasOwnProperty('reviewDate')) {
        obj['reviewDate'] = ApiClient.convertToType(data['reviewDate'], 'String');
      }
      if (data.hasOwnProperty('review')) {
        obj['review'] = ApiClient.convertToType(data['review'], 'String');
      }
      if (data.hasOwnProperty('translatedReview')) {
        obj['translatedReview'] = ApiClient.convertToType(data['translatedReview'], 'String');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], ['String']);
      }
      if (data.hasOwnProperty('shipping')) {
        obj['shipping'] = ApiClient.convertToType(data['shipping'], 'String');
      }
      if (data.hasOwnProperty('skuInformation')) {
        obj['skuInformation'] = ApiClient.convertToType(data['skuInformation'], 'String');
      }
      if (data.hasOwnProperty('downVotes')) {
        obj['downVotes'] = ApiClient.convertToType(data['downVotes'], 'Number');
      }
      if (data.hasOwnProperty('upVotes')) {
        obj['upVotes'] = ApiClient.convertToType(data['upVotes'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The name of the buyer of the product 
   * @member {String} buyerName
   */
  exports.prototype['buyerName'] = undefined;
  /**
   * The country of the buyer of the product 
   * @member {String} buyerCountry
   */
  exports.prototype['buyerCountry'] = undefined;
  /**
   * The rating provided by the buyer 
   * @member {Number} buyerRating
   */
  exports.prototype['buyerRating'] = undefined;
  /**
   * The date of the review 
   * @member {String} reviewDate
   */
  exports.prototype['reviewDate'] = undefined;
  /**
   * The actual review message 
   * @member {String} review
   */
  exports.prototype['review'] = undefined;
  /**
   * The translated review message 
   * @member {String} translatedReview
   */
  exports.prototype['translatedReview'] = undefined;
  /**
   * Images that have been posted with the review 
   * @member {Array.<String>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * The shipping chosen by the reviewer 
   * @member {String} shipping
   */
  exports.prototype['shipping'] = undefined;
  /**
   * The sku information of the product purchased 
   * @member {String} skuInformation
   */
  exports.prototype['skuInformation'] = undefined;
  /**
   * The number of downvotes on this review 
   * @member {Number} downVotes
   */
  exports.prototype['downVotes'] = undefined;
  /**
   * The number of upvotes on this review 
   * @member {Number} upVotes
   */
  exports.prototype['upVotes'] = undefined;



  return exports;
}));


