/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.ProductSeller = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ProductSeller model module.
   * @module model/ProductSeller
   * @version 1.0.4
   */

  /**
   * Constructs a new <code>ProductSeller</code>.
   * Seller of an AliExpress product 
   * @alias module:model/ProductSeller
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ProductSeller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductSeller} obj Optional instance to populate.
   * @return {module:model/ProductSeller} The populated <code>ProductSeller</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('storeId')) {
        obj['storeId'] = ApiClient.convertToType(data['storeId'], 'Number');
      }
      if (data.hasOwnProperty('storeUrl')) {
        obj['storeUrl'] = ApiClient.convertToType(data['storeUrl'], 'String');
      }
      if (data.hasOwnProperty('storeName')) {
        obj['storeName'] = ApiClient.convertToType(data['storeName'], 'String');
      }
      if (data.hasOwnProperty('sellerLevel')) {
        obj['sellerLevel'] = ApiClient.convertToType(data['sellerLevel'], 'String');
      }
      if (data.hasOwnProperty('positiveFeedbackRate')) {
        obj['positiveFeedbackRate'] = ApiClient.convertToType(data['positiveFeedbackRate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The ID of the seller store 
   * @member {Number} storeId
   */
  exports.prototype['storeId'] = undefined;
  /**
   * The URL of the seller store 
   * @member {String} storeUrl
   */
  exports.prototype['storeUrl'] = undefined;
  /**
   * The name of the seller store 
   * @member {String} storeName
   */
  exports.prototype['storeName'] = undefined;
  /**
   * The level of the seller 
   * @member {String} sellerLevel
   */
  exports.prototype['sellerLevel'] = undefined;
  /**
   * The positive feedback rate of the seller 
   * @member {Number} positiveFeedbackRate
   */
  exports.prototype['positiveFeedbackRate'] = undefined;



  return exports;
}));


