/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.RealtimeCurrency = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class RealtimeCurrency.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "AUD"
     * @const
     */
    "AUD": "AUD",
    /**
     * value: "BRL"
     * @const
     */
    "BRL": "BRL",
    /**
     * value: "CAD"
     * @const
     */
    "CAD": "CAD",
    /**
     * value: "CHF"
     * @const
     */
    "CHF": "CHF",
    /**
     * value: "CLP"
     * @const
     */
    "CLP": "CLP",
    /**
     * value: "EUR"
     * @const
     */
    "EUR": "EUR",
    /**
     * value: "GBP"
     * @const
     */
    "GBP": "GBP",
    /**
     * value: "IDR"
     * @const
     */
    "IDR": "IDR",
    /**
     * value: "KRW"
     * @const
     */
    "KRW": "KRW",
    /**
     * value: "NZD"
     * @const
     */
    "NZD": "NZD",
    /**
     * value: "PLN"
     * @const
     */
    "PLN": "PLN",
    /**
     * value: "RUB"
     * @const
     */
    "RUB": "RUB",
    /**
     * value: "SEK"
     * @const
     */
    "SEK": "SEK",
    /**
     * value: "SGD"
     * @const
     */
    "SGD": "SGD",
    /**
     * value: "TRY"
     * @const
     */
    "TRY": "TRY",
    /**
     * value: "UAH"
     * @const
     */
    "UAH": "UAH",
    /**
     * value: "USD"
     * @const
     */
    "USD": "USD"  };

  /**
   * Returns a <code>RealtimeCurrency</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/RealtimeCurrency} The enum <code>RealtimeCurrency</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


