/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.RealtimeSearchAggregation = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RealtimeSearchAggregation model module.
   * @module model/RealtimeSearchAggregation
   * @version 0.10.0
   */

  /**
   * Constructs a new <code>RealtimeSearchAggregation</code>.
   * The aggregated data from a realtime search 
   * @alias module:model/RealtimeSearchAggregation
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RealtimeSearchAggregation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RealtimeSearchAggregation} obj Optional instance to populate.
   * @return {module:model/RealtimeSearchAggregation} The populated <code>RealtimeSearchAggregation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('totalCount')) {
        obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
      }
      if (data.hasOwnProperty('shipFromCountries')) {
        obj['shipFromCountries'] = ApiClient.convertToType(data['shipFromCountries'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The total number of items that matched the request 
   * @member {Number} totalCount
   */
  exports.prototype['totalCount'] = undefined;
  /**
   * The countries that the items can ship from 
   * @member {Array.<String>} shipFromCountries
   */
  exports.prototype['shipFromCountries'] = undefined;



  return exports;
}));


