/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SearchAggregation', 'model/SearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SearchAggregation'), require('./SearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.SearchResponse = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.SearchAggregation, root.AliseeksApi.SearchItem);
  }
}(this, function(ApiClient, SearchAggregation, SearchItem) {
  'use strict';



  /**
   * The SearchResponse model module.
   * @module model/SearchResponse
   * @version 1.0.0-rc.1
   */

  /**
   * Constructs a new <code>SearchResponse</code>.
   * Aliseeks search response 
   * @alias module:model/SearchResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResponse} obj Optional instance to populate.
   * @return {module:model/SearchResponse} The populated <code>SearchResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('aggregation')) {
        obj['aggregation'] = SearchAggregation.constructFromObject(data['aggregation']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [SearchItem]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SearchAggregation} aggregation
   */
  exports.prototype['aggregation'] = undefined;
  /**
   * Search items that match the request 
   * @member {Array.<module:model/SearchItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


