/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/SearchItemFreight', 'model/SearchItemFreightType', 'model/SearchItemSeller'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./SearchItemFreight'), require('./SearchItemFreightType'), require('./SearchItemSeller'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.SearchItem = factory(root.AliseeksApi.ApiClient, root.AliseeksApi.Amount, root.AliseeksApi.SearchItemFreight, root.AliseeksApi.SearchItemFreightType, root.AliseeksApi.SearchItemSeller);
  }
}(this, function(ApiClient, Amount, SearchItemFreight, SearchItemFreightType, SearchItemSeller) {
  'use strict';



  /**
   * The SearchItem model module.
   * @module model/SearchItem
   * @version 1.0.0-rc.1
   */

  /**
   * Constructs a new <code>SearchItem</code>.
   * Aliseeks search item 
   * @alias module:model/SearchItem
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SearchItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchItem} obj Optional instance to populate.
   * @return {module:model/SearchItem} The populated <code>SearchItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('categoryId')) {
        obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'Number');
      }
      if (data.hasOwnProperty('imageUrl')) {
        obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
      }
      if (data.hasOwnProperty('detailUrl')) {
        obj['detailUrl'] = ApiClient.convertToType(data['detailUrl'], 'String');
      }
      if (data.hasOwnProperty('lotSize')) {
        obj['lotSize'] = ApiClient.convertToType(data['lotSize'], 'Number');
      }
      if (data.hasOwnProperty('lotUnit')) {
        obj['lotUnit'] = ApiClient.convertToType(data['lotUnit'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = Amount.constructFromObject(data['price']);
      }
      if (data.hasOwnProperty('ratings')) {
        obj['ratings'] = ApiClient.convertToType(data['ratings'], 'Number');
      }
      if (data.hasOwnProperty('orders')) {
        obj['orders'] = ApiClient.convertToType(data['orders'], 'Number');
      }
      if (data.hasOwnProperty('freight')) {
        obj['freight'] = SearchItemFreight.constructFromObject(data['freight']);
      }
      if (data.hasOwnProperty('seller')) {
        obj['seller'] = SearchItemSeller.constructFromObject(data['seller']);
      }
      if (data.hasOwnProperty('freightTypes')) {
        obj['freightTypes'] = ApiClient.convertToType(data['freightTypes'], [SearchItemFreightType]);
      }
    }
    return obj;
  }

  /**
   * AliExpress Product ID 
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The subject / title of the product 
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * The category of the item 
   * @member {Number} categoryId
   */
  exports.prototype['categoryId'] = undefined;
  /**
   * Image URL for the item 
   * @member {String} imageUrl
   */
  exports.prototype['imageUrl'] = undefined;
  /**
   * The detail URL of the item 
   * @member {String} detailUrl
   */
  exports.prototype['detailUrl'] = undefined;
  /**
   * The lot size that the item is sold in 
   * @member {Number} lotSize
   */
  exports.prototype['lotSize'] = undefined;
  /**
   * The unit when describing a lot for this item 
   * @member {String} lotUnit
   */
  exports.prototype['lotUnit'] = undefined;
  /**
   * @member {module:model/Amount} price
   */
  exports.prototype['price'] = undefined;
  /**
   * The ratings of this item 
   * @member {Number} ratings
   */
  exports.prototype['ratings'] = undefined;
  /**
   * The number of orders of this item 
   * @member {Number} orders
   */
  exports.prototype['orders'] = undefined;
  /**
   * @member {module:model/SearchItemFreight} freight
   */
  exports.prototype['freight'] = undefined;
  /**
   * @member {module:model/SearchItemSeller} seller
   */
  exports.prototype['seller'] = undefined;
  /**
   * List of freight types available for this item 
   * @member {Array.<module:model/SearchItemFreightType>} freightTypes
   */
  exports.prototype['freightTypes'] = undefined;



  return exports;
}));


