/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.TradeInformation = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The TradeInformation model module.
   * @module model/TradeInformation
   * @version 0.10.1
   */

  /**
   * Constructs a new <code>TradeInformation</code>.
   * Information regarding trade 
   * @alias module:model/TradeInformation
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>TradeInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TradeInformation} obj Optional instance to populate.
   * @return {module:model/TradeInformation} The populated <code>TradeInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('stock')) {
        obj['stock'] = ApiClient.convertToType(data['stock'], 'Number');
      }
      if (data.hasOwnProperty('sold')) {
        obj['sold'] = ApiClient.convertToType(data['sold'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The product stock 
   * @member {Number} stock
   */
  exports.prototype['stock'] = undefined;
  /**
   * The amount sold of the product
   * @member {Number} sold
   */
  exports.prototype['sold'] = undefined;



  return exports;
}));


