/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AliseeksApi) {
      root.AliseeksApi = {};
    }
    root.AliseeksApi.UploadImageResponse = factory(root.AliseeksApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The UploadImageResponse model module.
   * @module model/UploadImageResponse
   * @version 0.10.2
   */

  /**
   * Constructs a new <code>UploadImageResponse</code>.
   * The response from uploading an image 
   * @alias module:model/UploadImageResponse
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>UploadImageResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadImageResponse} obj Optional instance to populate.
   * @return {module:model/UploadImageResponse} The populated <code>UploadImageResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('uploadKey')) {
        obj['uploadKey'] = ApiClient.convertToType(data['uploadKey'], 'String');
      }
    }
    return obj;
  }

  /**
   * The upload key that should be used when performing an image search request 
   * @member {String} uploadKey
   */
  exports.prototype['uploadKey'] = undefined;



  return exports;
}));


