/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.PriceSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PriceSummary', function() {
    it('should create an instance of PriceSummary', function() {
      // uncomment below and update the code to test PriceSummary
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be.a(AliseeksApi.PriceSummary);
    });

    it('should have the property originalAmount (base name: "originalAmount")', function() {
      // uncomment below and update the code to test the property originalAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

    it('should have the property unitOriginalAmount (base name: "unitOriginalAmount")', function() {
      // uncomment below and update the code to test the property unitOriginalAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

    it('should have the property discountedAmount (base name: "discountedAmount")', function() {
      // uncomment below and update the code to test the property discountedAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

    it('should have the property unitDiscountedAmount (base name: "unitDiscountedAmount")', function() {
      // uncomment below and update the code to test the property unitDiscountedAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

    it('should have the property bulkAmount (base name: "bulkAmount")', function() {
      // uncomment below and update the code to test the property bulkAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

    it('should have the property unitBulkAmount (base name: "unitBulkAmount")', function() {
      // uncomment below and update the code to test the property unitBulkAmount
      //var instance = new AliseeksApi.PriceSummary();
      //expect(instance).to.be();
    });

  });

}));
