/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.ProductDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductDetail', function() {
    it('should create an instance of ProductDetail', function() {
      // uncomment below and update the code to test ProductDetail
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be.a(AliseeksApi.ProductDetail);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property categoryId (base name: "categoryId")', function() {
      // uncomment below and update the code to test the property categoryId
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "companyId")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property sellerId (base name: "sellerId")', function() {
      // uncomment below and update the code to test the property sellerId
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property productImages (base name: "productImages")', function() {
      // uncomment below and update the code to test the property productImages
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property statusId (base name: "statusId")', function() {
      // uncomment below and update the code to test the property statusId
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property countPerLot (base name: "countPerLot")', function() {
      // uncomment below and update the code to test the property countPerLot
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property wishListCount (base name: "wishListCount")', function() {
      // uncomment below and update the code to test the property wishListCount
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property multiUnit (base name: "multiUnit")', function() {
      // uncomment below and update the code to test the property multiUnit
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property promotions (base name: "promotions")', function() {
      // uncomment below and update the code to test the property promotions
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property prices (base name: "prices")', function() {
      // uncomment below and update the code to test the property prices
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property reviews (base name: "reviews")', function() {
      // uncomment below and update the code to test the property reviews
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property trade (base name: "trade")', function() {
      // uncomment below and update the code to test the property trade
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

    it('should have the property skuProperties (base name: "skuProperties")', function() {
      // uncomment below and update the code to test the property skuProperties
      //var instance = new AliseeksApi.ProductDetail();
      //expect(instance).to.be();
    });

  });

}));
