/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.ProductShippingOptions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductShippingOptions', function() {
    it('should create an instance of ProductShippingOptions', function() {
      // uncomment below and update the code to test ProductShippingOptions
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be.a(AliseeksApi.ProductShippingOptions);
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property serviceName (base name: "serviceName")', function() {
      // uncomment below and update the code to test the property serviceName
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property tracking (base name: "tracking")', function() {
      // uncomment below and update the code to test the property tracking
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property commitDays (base name: "commitDays")', function() {
      // uncomment below and update the code to test the property commitDays
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property shipFrom (base name: "shipFrom")', function() {
      // uncomment below and update the code to test the property shipFrom
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

    it('should have the property deliveryTime (base name: "deliveryTime")', function() {
      // uncomment below and update the code to test the property deliveryTime
      //var instance = new AliseeksApi.ProductShippingOptions();
      //expect(instance).to.be();
    });

  });

}));
