/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.ProductReviews();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductReviews', function() {
    it('should create an instance of ProductReviews', function() {
      // uncomment below and update the code to test ProductReviews
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be.a(AliseeksApi.ProductReviews);
    });

    it('should have the property fiveStarCount (base name: "fiveStarCount")', function() {
      // uncomment below and update the code to test the property fiveStarCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property fourStarCount (base name: "fourStarCount")', function() {
      // uncomment below and update the code to test the property fourStarCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property threeStarCount (base name: "threeStarCount")', function() {
      // uncomment below and update the code to test the property threeStarCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property twoStarCount (base name: "twoStarCount")', function() {
      // uncomment below and update the code to test the property twoStarCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property oneStarCount (base name: "oneStarCount")', function() {
      // uncomment below and update the code to test the property oneStarCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property totalCount (base name: "totalCount")', function() {
      // uncomment below and update the code to test the property totalCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property positiveCount (base name: "positiveCount")', function() {
      // uncomment below and update the code to test the property positiveCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property negativeCount (base name: "negativeCount")', function() {
      // uncomment below and update the code to test the property negativeCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property neutralCount (base name: "neutralCount")', function() {
      // uncomment below and update the code to test the property neutralCount
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

    it('should have the property ratings (base name: "ratings")', function() {
      // uncomment below and update the code to test the property ratings
      //var instance = new AliseeksApi.ProductReviews();
      //expect(instance).to.be();
    });

  });

}));
