/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.ProductReview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductReview', function() {
    it('should create an instance of ProductReview', function() {
      // uncomment below and update the code to test ProductReview
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be.a(AliseeksApi.ProductReview);
    });

    it('should have the property buyerName (base name: "buyerName")', function() {
      // uncomment below and update the code to test the property buyerName
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property buyerCountry (base name: "buyerCountry")', function() {
      // uncomment below and update the code to test the property buyerCountry
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property buyerRating (base name: "buyerRating")', function() {
      // uncomment below and update the code to test the property buyerRating
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property reviewDate (base name: "reviewDate")', function() {
      // uncomment below and update the code to test the property reviewDate
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property review (base name: "review")', function() {
      // uncomment below and update the code to test the property review
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property translatedReview (base name: "translatedReview")', function() {
      // uncomment below and update the code to test the property translatedReview
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property shipping (base name: "shipping")', function() {
      // uncomment below and update the code to test the property shipping
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property skuInformation (base name: "skuInformation")', function() {
      // uncomment below and update the code to test the property skuInformation
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property downVotes (base name: "downVotes")', function() {
      // uncomment below and update the code to test the property downVotes
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

    it('should have the property upVotes (base name: "upVotes")', function() {
      // uncomment below and update the code to test the property upVotes
      //var instance = new AliseeksApi.ProductReview();
      //expect(instance).to.be();
    });

  });

}));
