/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.PromotionOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromotionOption', function() {
    it('should create an instance of PromotionOption', function() {
      // uncomment below and update the code to test PromotionOption
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be.a(AliseeksApi.PromotionOption);
    });

    it('should have the property maxAmount (base name: "maxAmount")', function() {
      // uncomment below and update the code to test the property maxAmount
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be();
    });

    it('should have the property minAmount (base name: "minAmount")', function() {
      // uncomment below and update the code to test the property minAmount
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be();
    });

    it('should have the property timeLeft (base name: "timeLeft")', function() {
      // uncomment below and update the code to test the property timeLeft
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instance = new AliseeksApi.PromotionOption();
      //expect(instance).to.be();
    });

  });

}));
