/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 0.10.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.SearchRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchRequest', function() {
    it('should create an instance of SearchRequest', function() {
      // uncomment below and update the code to test SearchRequest
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be.a(AliseeksApi.SearchRequest);
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property sort (base name: "sort")', function() {
      // uncomment below and update the code to test the property sort
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeSubcategories (base name: "includeSubcategories")', function() {
      // uncomment below and update the code to test the property includeSubcategories
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property sortDirection (base name: "sortDirection")', function() {
      // uncomment below and update the code to test the property sortDirection
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property ratingsRange (base name: "ratingsRange")', function() {
      // uncomment below and update the code to test the property ratingsRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property quantityRange (base name: "quantityRange")', function() {
      // uncomment below and update the code to test the property quantityRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property priceRange (base name: "priceRange")', function() {
      // uncomment below and update the code to test the property priceRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property unitPriceRange (base name: "unitPriceRange")', function() {
      // uncomment below and update the code to test the property unitPriceRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property orderRange (base name: "orderRange")', function() {
      // uncomment below and update the code to test the property orderRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property itemIdRange (base name: "itemIdRange")', function() {
      // uncomment below and update the code to test the property itemIdRange
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property freightTypes (base name: "freightTypes")', function() {
      // uncomment below and update the code to test the property freightTypes
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property skip (base name: "skip")', function() {
      // uncomment below and update the code to test the property skip
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property limit (base name: "limit")', function() {
      // uncomment below and update the code to test the property limit
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property scrollPagination (base name: "scrollPagination")', function() {
      // uncomment below and update the code to test the property scrollPagination
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property scrollIdentifier (base name: "scrollIdentifier")', function() {
      // uncomment below and update the code to test the property scrollIdentifier
      //var instance = new AliseeksApi.SearchRequest();
      //expect(instance).to.be();
    });

  });

}));
