/**
 * Aliseeks API
 * AliExpress product searching and product details retrieval API. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AliseeksApi);
  }
}(this, function(expect, AliseeksApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AliseeksApi.SkuPriceOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SkuPriceOption', function() {
    it('should create an instance of SkuPriceOption', function() {
      // uncomment below and update the code to test SkuPriceOption
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be.a(AliseeksApi.SkuPriceOption);
    });

    it('should have the property originalPrice (base name: "originalPrice")', function() {
      // uncomment below and update the code to test the property originalPrice
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property discountedPrice (base name: "discountedPrice")', function() {
      // uncomment below and update the code to test the property discountedPrice
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property bulkPrice (base name: "bulkPrice")', function() {
      // uncomment below and update the code to test the property bulkPrice
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property bulkQuantity (base name: "bulkQuantity")', function() {
      // uncomment below and update the code to test the property bulkQuantity
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property skuImage (base name: "skuImage")', function() {
      // uncomment below and update the code to test the property skuImage
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property discountedStock (base name: "discountedStock")', function() {
      // uncomment below and update the code to test the property discountedStock
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property skuIdentifier (base name: "skuIdentifier")', function() {
      // uncomment below and update the code to test the property skuIdentifier
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instance = new AliseeksApi.SkuPriceOption();
      //expect(instance).to.be();
    });

  });

}));
